Server:
  RunMode: debug
  HttpPort: 8080
  ReadTimeout: 60
  WriteTimeout: 60
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
Database:
  DBType: mysql
  Username: root
  Password: 123456
  Host: koreyoshi.work
  DBName: blog_service
  TablePrefix: blog_
  Charset: utf8mb4
  ParseTime: true
  MaxIdleConns: 10
  MaxOpenConns: 30